package gui.simulator;

import benchmarking.simulatorconfiguration.HybridConfig;
import benchmarking.simulatorconfiguration.ODEConfig;
import benchmarking.simulatorconfiguration.SSAConfig;
import benchmarking.simulatorconfiguration.TAUConfig;
import core.util.IO;

/**
 *
 * @author Martin
 */
public class HybridSimulatorPanel extends javax.swing.JPanel {

    private SSAConfig configSSA;
    private TAUConfig configTAU;
    private ODEConfig configODE;
    
    /**
     * Creates new form HybridSimulatorPanel
     * @param initial
     */
    public HybridSimulatorPanel(HybridConfig initial) {
        initComponents();
        
        setHybridConfig(initial);
    }
    
    public final void setHybridConfig(HybridConfig conf) {
        configSSA = (SSAConfig) conf.getSSAConfig().copy();
        configTAU = (TAUConfig) conf.getTAUConfig().copy();
        configODE = (ODEConfig) conf.getODEConfig().copy();
        
        spinnerThresholdTAU.setValue(conf.getThresholdTAU());
        spinnerThresholdODE.setValue(conf.getThresholdODE());
        sliderFactorSSA2TAU.setValue((int) Math.round(conf.getFactorSSA2TAU()* 100));
        sliderFactorTAU2ODE.setValue((int) Math.round(conf.getFactorTAU2ODE()* 100));
    }
    
    public HybridConfig getHybridConfig() {
        return new HybridConfig()
                .setSSAConfig(configSSA)
                .setTAUConfig(configTAU)
                .setODEConfig(configODE)
                .setThresholdTau(Integer.parseInt(spinnerThresholdTAU.getValue().toString()))
                .setThresholdODE(Integer.parseInt(spinnerThresholdODE.getValue().toString()))
                .setFactorSSAToTAU(Double.parseDouble(textFieldFactorSSA2TAU.getText()))
                .setFactorTAUToODE(Double.parseDouble(textFieldFactorTAU2ODE.getText()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelSimulators = new javax.swing.JLabel();
        buttonSSA = new javax.swing.JButton();
        buttonTAU = new javax.swing.JButton();
        buttonODE = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        spinnerThresholdTAU = new javax.swing.JSpinner();
        spinnerThresholdODE = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        labelSSA2TAU = new javax.swing.JLabel();
        textFieldFactorSSA2TAU = new javax.swing.JTextField();
        sliderFactorSSA2TAU = new javax.swing.JSlider();
        labelTAU2ODE = new javax.swing.JLabel();
        textFieldFactorTAU2ODE = new javax.swing.JTextField();
        sliderFactorTAU2ODE = new javax.swing.JSlider();

        labelSimulators.setText("Simulators:");

        buttonSSA.setText("SSA");
        buttonSSA.setEnabled(false);
        buttonSSA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSSAActionPerformed(evt);
            }
        });

        buttonTAU.setText("TAU");
        buttonTAU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTAUActionPerformed(evt);
            }
        });

        buttonODE.setText("ODE");
        buttonODE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonODEActionPerformed(evt);
            }
        });

        jLabel1.setText("Thresholds:");

        spinnerThresholdTAU.setModel(new javax.swing.SpinnerNumberModel(5, 0, null, 1));

        spinnerThresholdODE.setModel(new javax.swing.SpinnerNumberModel(400, 10, null, 1));

        jLabel2.setText("Factors:");

        labelSSA2TAU.setText("SSA 2 TAU:");

        textFieldFactorSSA2TAU.setEditable(false);
        textFieldFactorSSA2TAU.setText("2.0");

        sliderFactorSSA2TAU.setMaximum(1000);
        sliderFactorSSA2TAU.setMinimum(100);
        sliderFactorSSA2TAU.setToolTipText("");
        sliderFactorSSA2TAU.setValue(200);
        sliderFactorSSA2TAU.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFactorSSA2TAUStateChanged(evt);
            }
        });

        labelTAU2ODE.setText("TAU 2 ODE:");

        textFieldFactorTAU2ODE.setEditable(false);
        textFieldFactorTAU2ODE.setText("2.0");

        sliderFactorTAU2ODE.setMaximum(1000);
        sliderFactorTAU2ODE.setMinimum(100);
        sliderFactorTAU2ODE.setToolTipText("");
        sliderFactorTAU2ODE.setValue(200);
        sliderFactorTAU2ODE.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sliderFactorTAU2ODEStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSimulators)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonSSA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelSSA2TAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelTAU2ODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(textFieldFactorTAU2ODE)
                    .addComponent(spinnerThresholdTAU)
                    .addComponent(buttonTAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(textFieldFactorSSA2TAU))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(spinnerThresholdODE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(sliderFactorSSA2TAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sliderFactorTAU2ODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSSA)
                    .addComponent(buttonTAU)
                    .addComponent(buttonODE)
                    .addComponent(labelSimulators))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(spinnerThresholdTAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spinnerThresholdODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(labelSSA2TAU)
                        .addComponent(textFieldFactorSSA2TAU, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderFactorSSA2TAU, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(labelTAU2ODE)
                        .addComponent(textFieldFactorTAU2ODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(sliderFactorTAU2ODE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSSAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSSAActionPerformed
        SSAConfig newSSAConfig = (SSAConfig) SimulatorConfigEditor.edit(configSSA);
        if (newSSAConfig != null) this.configSSA = newSSAConfig;
    }//GEN-LAST:event_buttonSSAActionPerformed

    private void buttonTAUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTAUActionPerformed
        TAUConfig newTAUConfig = (TAUConfig) SimulatorConfigEditor.edit(configTAU);
        if (newTAUConfig != null) this.configTAU = newTAUConfig;
    }//GEN-LAST:event_buttonTAUActionPerformed

    private void buttonODEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonODEActionPerformed
        ODEConfig newODEConfig = (ODEConfig) SimulatorConfigEditor.edit(configODE);
        if (newODEConfig != null) this.configODE = newODEConfig;
    }//GEN-LAST:event_buttonODEActionPerformed

    private void sliderFactorSSA2TAUStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFactorSSA2TAUStateChanged
        textFieldFactorSSA2TAU.setText(IO.significantFigures(1.0 / 100 * sliderFactorSSA2TAU.getValue()));
    }//GEN-LAST:event_sliderFactorSSA2TAUStateChanged

    private void sliderFactorTAU2ODEStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderFactorTAU2ODEStateChanged
        textFieldFactorTAU2ODE.setText(IO.significantFigures(1.0 / 100 * sliderFactorTAU2ODE.getValue()));
    }//GEN-LAST:event_sliderFactorTAU2ODEStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonODE;
    private javax.swing.JButton buttonSSA;
    private javax.swing.JButton buttonTAU;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelSSA2TAU;
    private javax.swing.JLabel labelSimulators;
    private javax.swing.JLabel labelTAU2ODE;
    private javax.swing.JSlider sliderFactorSSA2TAU;
    private javax.swing.JSlider sliderFactorTAU2ODE;
    private javax.swing.JSpinner spinnerThresholdODE;
    private javax.swing.JSpinner spinnerThresholdTAU;
    private javax.swing.JTextField textFieldFactorSSA2TAU;
    private javax.swing.JTextField textFieldFactorTAU2ODE;
    // End of variables declaration//GEN-END:variables
}
